package com.wynnlab.minestom.particle.minestom;

import com.wynnlab.minestom.particle.adventure.Nothing;
import com.wynnlab.minestom.particle.minestom.extra.*;
import com.wynnlab.minestom.particle.minestom.ParticleTypes.Color;
import com.wynnlab.minestom.particle.minestom.ParticleTypes.OffsetAndSpeed;
import net.minestom.server.particle.Particle;

@SuppressWarnings("all")
public interface ParticleType {
    ParticleTypes<Color, Nothing> AMBIENT_ENTITY_EFFECT = new ParticleTypes.ColorParticleType(Particle.AMBIENT_ENTITY_EFFECT);
    ParticleTypes<OffsetAndSpeed, Nothing> ANGRY_VILLAGER = new ParticleTypes.DefaultParticleType(Particle.ANGRY_VILLAGER);
    ParticleTypes<OffsetAndSpeed, BlockState> BLOCK = new ParticleTypes.Block(Particle.BLOCK);
    ParticleTypes<OffsetAndSpeed, Nothing> BUBBLE = new ParticleTypes.DefaultParticleType(Particle.BUBBLE);
    ParticleTypes<OffsetAndSpeed, Nothing> CLOUD = new ParticleTypes.DefaultParticleType(Particle.CLOUD);
    ParticleTypes<OffsetAndSpeed, Nothing> CRIT = new ParticleTypes.DefaultParticleType(Particle.CRIT);
    ParticleTypes<OffsetAndSpeed, Nothing> DAMAGE_INDICATOR = new ParticleTypes.DefaultParticleType(Particle.DAMAGE_INDICATOR);
    ParticleTypes<OffsetAndSpeed, Nothing> DRAGON_BREATH = new ParticleTypes.DefaultParticleType(Particle.DRAGON_BREATH);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_LAVA = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_LAVA = new ParticleTypes.DefaultParticleType(Particle.FALLING_LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> LANDING_LAVA = new ParticleTypes.DefaultParticleType(Particle.LANDING_LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_WATER = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_WATER);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_WATER = new ParticleTypes.DefaultParticleType(Particle.FALLING_WATER);
    ParticleTypes<OffsetAndSpeed, Dust> DUST = ParticleTypes.DUST.INSTANCE;
    ParticleTypes<OffsetAndSpeed, DustTransition> DUST_COLOR_TRANSITION = ParticleTypes.DUST_COLOR_TRANSITION.INSTANCE;
    ParticleTypes<Color, Nothing> EFFECT = new ParticleTypes.ColorParticleType(Particle.EFFECT);
    ParticleTypes<OffsetAndSpeed, Nothing> ELDER_GUARDIAN = new ParticleTypes.DefaultParticleType(Particle.ELDER_GUARDIAN);
    ParticleTypes<OffsetAndSpeed, Nothing> ENCHANTED_HIT = new ParticleTypes.DefaultParticleType(Particle.ENCHANTED_HIT);
    ParticleTypes<OffsetAndSpeed, Nothing> ENCHANT = new ParticleTypes.DefaultParticleType(Particle.ENCHANT);
    ParticleTypes<OffsetAndSpeed, Nothing> END_ROD = new ParticleTypes.DefaultParticleType(Particle.END_ROD);
    ParticleTypes<Color, Nothing> ENTITY_EFFECT = new ParticleTypes.ColorParticleType(Particle.ENTITY_EFFECT);
    ParticleTypes<OffsetAndSpeed, Nothing> EXPLOSION_EMITTER = new ParticleTypes.DefaultParticleType(Particle.EXPLOSION_EMITTER);
    ParticleTypes<OffsetAndSpeed, Nothing> EXPLOSION = new ParticleTypes.DefaultParticleType(Particle.EXPLOSION);
    ParticleTypes<OffsetAndSpeed, BlockState> FALLING_DUST = new ParticleTypes.Block(Particle.FALLING_DUST);
    ParticleTypes<OffsetAndSpeed, Nothing> FIREWORK = new ParticleTypes.DefaultParticleType(Particle.FIREWORK);
    ParticleTypes<OffsetAndSpeed, Nothing> FISHING = new ParticleTypes.DefaultParticleType(Particle.FISHING);
    ParticleTypes<OffsetAndSpeed, Nothing> FLAME = new ParticleTypes.DefaultParticleType(Particle.FLAME);
    ParticleTypes<OffsetAndSpeed, Nothing> SOUL_FIRE_FLAME = new ParticleTypes.DefaultParticleType(Particle.SOUL_FIRE_FLAME);
    ParticleTypes<OffsetAndSpeed, Nothing> SOUL = new ParticleTypes.DefaultParticleType(Particle.SOUL);
    ParticleTypes<OffsetAndSpeed, Nothing> FLASH = new ParticleTypes.DefaultParticleType(Particle.FLASH);
    ParticleTypes<OffsetAndSpeed, Nothing> HAPPY_VILLAGER = new ParticleTypes.DefaultParticleType(Particle.HAPPY_VILLAGER);
    ParticleTypes<OffsetAndSpeed, Nothing> COMPOSTER = new ParticleTypes.DefaultParticleType(Particle.COMPOSTER);
    ParticleTypes<OffsetAndSpeed, Nothing> HEART = new ParticleTypes.DefaultParticleType(Particle.HEART);
    ParticleTypes<Color, Nothing> INSTANT_EFFECT = new ParticleTypes.ColorParticleType(Particle.INSTANT_EFFECT);
    ParticleTypes<OffsetAndSpeed, Item> ITEM = ParticleTypes.ITEM.INSTANCE;
    ParticleTypes<OffsetAndSpeed, Vibration> VIBRATION = ParticleTypes.VIBRATION.INSTANCE;
    ParticleTypes<OffsetAndSpeed, Nothing> ITEM_SLIME = new ParticleTypes.DefaultParticleType(Particle.ITEM_SLIME);
    ParticleTypes<OffsetAndSpeed, Nothing> ITEM_SNOWBALL = new ParticleTypes.DefaultParticleType(Particle.ITEM_SNOWBALL);
    ParticleTypes<OffsetAndSpeed, Nothing> LARGE_SMOKE = new ParticleTypes.DefaultParticleType(Particle.LARGE_SMOKE);
    ParticleTypes<OffsetAndSpeed, Nothing> LAVA = new ParticleTypes.DefaultParticleType(Particle.LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> MYCELIUM = new ParticleTypes.DefaultParticleType(Particle.MYCELIUM);
    ParticleTypes<OffsetAndSpeed, Nothing> NOTE = new ParticleTypes.DefaultParticleType(Particle.NOTE);
    ParticleTypes<OffsetAndSpeed, Nothing> POOF = new ParticleTypes.DefaultParticleType(Particle.POOF);
    ParticleTypes<OffsetAndSpeed, Nothing> PORTAL = new ParticleTypes.DefaultParticleType(Particle.PORTAL);
    ParticleTypes<OffsetAndSpeed, Nothing> RAIN = new ParticleTypes.DefaultParticleType(Particle.RAIN);
    ParticleTypes<OffsetAndSpeed, Nothing> SMOKE = new ParticleTypes.DefaultParticleType(Particle.SMOKE);
    ParticleTypes<OffsetAndSpeed, Nothing> SNEEZE = new ParticleTypes.DefaultParticleType(Particle.SNEEZE);
    ParticleTypes<OffsetAndSpeed, Nothing> SPIT = new ParticleTypes.DefaultParticleType(Particle.SPIT);
    ParticleTypes<OffsetAndSpeed, Nothing> SQUID_INK = new ParticleTypes.DefaultParticleType(Particle.SQUID_INK);
    ParticleTypes<OffsetAndSpeed, Nothing> SWEEP_ATTACK = new ParticleTypes.DefaultParticleType(Particle.SWEEP_ATTACK);
    ParticleTypes<OffsetAndSpeed, Nothing> TOTEM_OF_UNDYING = new ParticleTypes.DefaultParticleType(Particle.TOTEM_OF_UNDYING);
    ParticleTypes<OffsetAndSpeed, Nothing> UNDERWATER = new ParticleTypes.DefaultParticleType(Particle.UNDERWATER);
    ParticleTypes<OffsetAndSpeed, Nothing> SPLASH = new ParticleTypes.DefaultParticleType(Particle.SPLASH);
    ParticleTypes<OffsetAndSpeed, Nothing> WITCH = new ParticleTypes.DefaultParticleType(Particle.WITCH);
    ParticleTypes<OffsetAndSpeed, Nothing> BUBBLE_POP = new ParticleTypes.DefaultParticleType(Particle.BUBBLE_POP);
    ParticleTypes<OffsetAndSpeed, Nothing> CURRENT_DOWN = new ParticleTypes.DefaultParticleType(Particle.CURRENT_DOWN);
    ParticleTypes<OffsetAndSpeed, Nothing> BUBBLE_COLUMN_UP = new ParticleTypes.DefaultParticleType(Particle.BUBBLE_COLUMN_UP);
    ParticleTypes<OffsetAndSpeed, Nothing> NAUTILUS = new ParticleTypes.DefaultParticleType(Particle.NAUTILUS);
    ParticleTypes<OffsetAndSpeed, Nothing> DOLPHIN = new ParticleTypes.DefaultParticleType(Particle.DOLPHIN);
    ParticleTypes<OffsetAndSpeed, Nothing> CAMPFIRE_COSY_SMOKE = new ParticleTypes.DefaultParticleType(Particle.CAMPFIRE_COSY_SMOKE);
    ParticleTypes<OffsetAndSpeed, Nothing> CAMPFIRE_SIGNAL_SMOKE = new ParticleTypes.DefaultParticleType(Particle.CAMPFIRE_SIGNAL_SMOKE);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_HONEY = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_HONEY);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_HONEY = new ParticleTypes.DefaultParticleType(Particle.FALLING_HONEY);
    ParticleTypes<OffsetAndSpeed, Nothing> LANDING_HONEY = new ParticleTypes.DefaultParticleType(Particle.LANDING_HONEY);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_NECTAR = new ParticleTypes.DefaultParticleType(Particle.FALLING_NECTAR);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_SPORE_BLOSSOM = new ParticleTypes.DefaultParticleType(Particle.FALLING_SPORE_BLOSSOM);
    ParticleTypes<OffsetAndSpeed, Nothing> ASH = new ParticleTypes.DefaultParticleType(Particle.ASH);
    ParticleTypes<OffsetAndSpeed, Nothing> CRIMSON_SPORE = new ParticleTypes.DefaultParticleType(Particle.CRIMSON_SPORE);
    ParticleTypes<OffsetAndSpeed, Nothing> WARPED_SPORE = new ParticleTypes.DefaultParticleType(Particle.WARPED_SPORE);
    ParticleTypes<OffsetAndSpeed, Nothing> SPORE_BLOSSOM_AIR = new ParticleTypes.DefaultParticleType(Particle.SPORE_BLOSSOM_AIR);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_OBSIDIAN_TEAR = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_OBSIDIAN_TEAR);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_OBSIDIAN_TEAR = new ParticleTypes.DefaultParticleType(Particle.FALLING_OBSIDIAN_TEAR);
    ParticleTypes<OffsetAndSpeed, Nothing> LANDING_OBSIDIAN_TEAR = new ParticleTypes.DefaultParticleType(Particle.LANDING_OBSIDIAN_TEAR);
    ParticleTypes<OffsetAndSpeed, Nothing> REVERSE_PORTAL = new ParticleTypes.DefaultParticleType(Particle.REVERSE_PORTAL);
    ParticleTypes<OffsetAndSpeed, Nothing> WHITE_ASH = new ParticleTypes.DefaultParticleType(Particle.WHITE_ASH);
    ParticleTypes<OffsetAndSpeed, Nothing> SMALL_FLAME = new ParticleTypes.DefaultParticleType(Particle.SMALL_FLAME);
    ParticleTypes<OffsetAndSpeed, Nothing> SNOWFLAKE = new ParticleTypes.DefaultParticleType(Particle.SNOWFLAKE);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_DRIPSTONE_LAVA = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_DRIPSTONE_LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_DRIPSTONE_LAVA = new ParticleTypes.DefaultParticleType(Particle.FALLING_DRIPSTONE_LAVA);
    ParticleTypes<OffsetAndSpeed, Nothing> DRIPPING_DRIPSTONE_WATER = new ParticleTypes.DefaultParticleType(Particle.DRIPPING_DRIPSTONE_WATER);
    ParticleTypes<OffsetAndSpeed, Nothing> FALLING_DRIPSTONE_WATER = new ParticleTypes.DefaultParticleType(Particle.FALLING_DRIPSTONE_WATER);
    ParticleTypes<OffsetAndSpeed, Nothing> GLOW_SQUID_INK = new ParticleTypes.DefaultParticleType(Particle.GLOW_SQUID_INK);
    ParticleTypes<OffsetAndSpeed, Nothing> GLOW = new ParticleTypes.DefaultParticleType(Particle.GLOW);
    ParticleTypes<OffsetAndSpeed, Nothing> WAX_ON = new ParticleTypes.DefaultParticleType(Particle.WAX_ON);
    ParticleTypes<OffsetAndSpeed, Nothing> WAX_OFF = new ParticleTypes.DefaultParticleType(Particle.WAX_OFF);
    ParticleTypes<OffsetAndSpeed, Nothing> ELECTRIC_SPARK = new ParticleTypes.DefaultParticleType(Particle.ELECTRIC_SPARK);
    ParticleTypes<OffsetAndSpeed, Nothing> SCRAPE = new ParticleTypes.DefaultParticleType(Particle.SCRAPE);
}
